version: '3.8'

services:
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - backend

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
    networks:
      - backend

  owner-service:
    build: ./owner-service
    container_name: owner-service
    ports:
      - "8081:8081"
    depends_on:
      - discovery-service
    networks:
      - backend

  pet-service:
    build: ./pet-service
    container_name: pet-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery-service
    networks:
      - backend

  frontend:
    build: ./owner-pet-frontend
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - api-gateway
    networks:
      - backend

networks:
  backend:
