server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: owner-service
              uri: lb://owner-service
              predicates:
                - Path=/owners/**
            - id: pet-service
              uri: lb://pet-service
              predicates:
                - Path=/pets/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
